version: '3'

services:
  v2ray-tcp:
    image: v2cc/poseidon
    container_name: v2ray-tcp
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - /root/v2ray-poseidon/docker/v2board/ws-tls/config.json:/etc/v2ray/config.json
    logging:
      driver: "json-file"
      options:
        max-size: 2g
