version: '3'

services:
  v2ray-ws-tls:
    image: v2cc/poseidon
    container_name: v2ray-ws-tls
    restart: always
    ports:
      - "9000:9000"
      #- "80:80"
    volumes:
      - /root/v2ray-poseidon/docker/v2board/ws-tls/config.json:/etc/v2ray/config.json
      #- ./v2ray.crt:/etc/v2ray/v2ray.crt
      #- ./v2ray.key:/etc/v2ray/v2ray.key
    environment:
      # 手动指定证书文件，配置文件需要映射到容器里面
      #- CERT_FILE=/etc/v2ray/v2ray.crt
      #- KEY_FILE=/etc/v2ray/v2ray.key

      # 让程序自动生成 TLS 证书，支持 http 和 dns 两种方式
      # 若使用 http 方式获取证书，需要将 80 端口映射到主机并放行
      - CERT_MODE=dns
      # dns_cf 或 dns_namesilo 或 dns_namecheap
      - DNS_PROVIDER=dns_cf
      # 申请 DNS 证书的域名
      - CERT_DOMAIN=.wouw.cc
      # 使用 cloudflare DNS 验证
      - CF_Email=lusalem@gmail.com
      - CF_Key=7f5c92f79fd08a52f6bb6547e55c02145f347
      # 使用 namesilo DNS 验证
      - Namesilo_Key=
      # 使用 namecheap DNS 验证
      - NAMECHEAP_USERNAME=
      - NAMECHEAP_API_KEY=
    logging:
      driver: "json-file"
      options:
        max-size: 2g
